name: Create container, push and deploy

on:
  release:
    types: [published]
  push:
    branches: [development] #remove after

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip deploy')" # will not run if the commit contains that phrase
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Docker Meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/tow96/MasOrdenTool

      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1.0.1
        with:
          platforms: linux/amd64,linux/arm/v8

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.0.4 

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          platforms: linux/amd64,linux/arm/v8
          target: 'prod'
          file: ./Dockerfile

  # build-amd64:
  #   if: "!contains(github.event.head_commit.message, 'skip deploy')" # will not run if the commit contains that phrase
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         submodules: true

  #     - name: Docker Meta
  #       id: docker_meta
  #       uses: crazy-max/ghaction-docker-meta@v1
  #       with:
  #         images: ghcr.io/tow96/MasOrdenTool
  #         tag-sha: false
  #         tag-edge: false
  #         tag-latest: true

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Login to GHCR
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.repository_owner }}
  #         password: ${{ secrets.GHCR_PAT }}

  #     - name: Build and push image
  #       uses: docker/build-push-action@v2
  #       with:
  #         push: true
  #         tags: ${{ steps.docker_meta.outputs.tags }}
  #         target: 'prod'
  #         file: ./Dockerfile
  
  # build-arm:
  #   if: "!contains(github.event.head_commit.message, 'skip deploy')" # will not run if the commit contains that phrase
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         submodules: true

  #     - name: Docker Meta
  #       id: docker_meta
  #       uses: crazy-max/ghaction-docker-meta@v1
  #       with:
  #         images: ghcr.io/tow96/MasOrdenTool
  #         tag-sha: false
  #         tag-edge: false
  #         tag-latest: false
  #         tags: |
  #           type=raw,value=arm

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
  #       with:
  #         platforms: 'arm64,arm'

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Login to GHCR
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.repository_owner }}
  #         password: ${{ secrets.GHCR_PAT }}

  #     - name: Build and push image
  #       uses: docker/build-push-action@v2
  #       with:
  #         push: true
  #         tags: ${{ steps.docker_meta.outputs.tags }}
  #         target: 'prod'
  #         file: ./Dockerfile
